#!/bin/sh

set -e

# Set Hostname
echo "andalask8s" > /etc/hostname

# Update MOTD (Message of the Day)
cat <<EOF > /etc/motd

      _                _       _           _       ___  
     / \   _ __   __| | __ _| | __ _ ___| | __  ( _ ) 
    / _ \ | '_ \ / _\` |/ _\` | |/ _\` / __| |/ /  / _ \ 
   / ___ \| | | | (_| | (_| | | (_| \__ \   <  | (_) |
  /_/   \_\_| |_|\__,_|\__,_|_|\__,_|___/_|\_\  \___/ 

  Welcome to andalask8s - Custom Kubernetes Server Distro
  Based on Debian Bookworm (x86_64)
  
  Pre-installed: Docker, kubeadm, kubelet, kubectl
  
EOF

# Ensure the banner shows up on login
echo "cat /etc/motd" >> /etc/profile
